@startuml featureModel

!log tentando fazer os modelos de features de acordo com a Api ReactFeature

!procedure $optionalfeature($feature, $aparecer)
!if ($aparecer==1)
  OptionalAparece -> $feature.children 
!else
  OptionalNaoAparece ->
!endif
!endprocedure

!procedure $alternativefeature($feature,$optional,$resultlength)
    !if ($optional==1) && ($resultlength==0) 
      $optionalfeature($feature,1)
    !elseif (resultlength==0) && ($optional==0)
      princesa -> nao esta nesse castelo.
    !else
      $mandatoryfeature($feature)    
    !endif 
!endprocedure

!procedure $mandatoryfeature($feature)
    Mandatory -> $feature.children
!endprocedure

!$parent = { "oi" : "meu amigo jonny"}

!$children = { "banana" : "na caixa"}

!$teste = "supercaligraphilistic"

!$feature = { "name": "banana na caixa", "parent" : "donkey kong", "children" : "luigi", "component": "meu componente" }

!$relation = { "mandatory" : "oi", "optional" : 1, "alternative" : 0 }

!$aparecer = 1

!log rescreve a variavel apenas se ela for undefined
!$teste ?= "super"

!log reatribui um novo valor na variável assim:
!$teste = $parent.oi

Alice -> Bob : This is $feature.parent
Alice -> Bob : This is $teste

$mandatoryfeature($feature)

$optionalfeature($feature, $aparecer)

$alternativefeature($feature, 0, 0)

@enduml