@startsalt elementos
{
    !procedure $renderiza($leftbracket,$rightbracket,$midlelement)
        $leftbracket $midlelement $rightbracket
    !endprocedure

    $renderiza("[","]","botao")

}
@endsalt