@startsalt carrinho personalizado
{S
    'These don't use the function to convert in pegjs, just for plantUML use only

    !include https://raw.githubusercontent.com/JoseCarlosDeJesus/PLANTUML-features/main/EstudoDeCasoFeature/definitivefeature.puml
    
    !$aparecer = 1
    !$desktop = 1

    $optional(0,"","%chr(34) Pesquise Aqui %chr(34) |","",$aparecer)

    $alternative(1,{*,Produtos | <b>Meu Carrinho | Meu Perfil,},$desktop,{*,<&menu> | <&cart>,},0)

    $mandatory(1, {T-,"Descrição | Quantidade | Valor | Total %newline() Notebook  |  1 | 69 |30 %newline() Maçã | 1 | 89 | 90",})
    $mandatory(0,"","Total | R$ 898990","")
    $mandatory(0,[,"Confirmar Compra",])

}
@endsalt