@startsalt featuredefinitive
{
    !unquoted procedure $mandatory($multi, $leftbracket, $midlelement, $rightbracket)
    !if ($multi==1)
         $leftbracket %newline() $midlelement $rightbracket
    !else
        $leftbracket $midlelement $rightbracket
    !endif    

    !endprocedure

    !unquoted procedure $optional($multi, $leftbracket, $midlelement, $rightbracket, $aparecer)
        !if ($aparecer==1)
            $mandatory($multi, $leftbracket, $midlelement, $rightbracket) 
        !endif
    !endprocedure

    !unquoted procedure $alternative($multi,$leftbracket, $midlelement, $rightbracket, $plataforma, $leftalternative,$midlealternative,$rightalternative,$multialternative)
        !if ($plataforma==0) 
             $mandatory($multi, $leftbracket, $midlelement, $rightbracket)
        !elseif ($plataforma==1)
            $mandatory($multialternative, $leftalternative, $midlealternative, $rightalternative)   
        !endif 
    !endprocedure

    !unquoted procedure $mandatoryInput($midlelement)
        "$midlelement"
    !endprocedure

    !unquoted procedure $optionalInput($midlelement, $aparecer)
        !if ($aparecer==1)
            $mandatoryInput($midlelement) 
        !endif
    !endprocedure

    !unquoted procedure $alternativeInput($midlelement, $plataforma, $midlealternative)
        !if ($plataforma==0) 
             $mandatoryInput($midlelement)
        !elseif ($plataforma==1)
            $mandatoryInput($midlealternative)   
        !endif 
    !endprocedure


}
@endsalt