@startsalt featuredefinitive
{
    !unquoted procedure $mandatory($namecomponent,$multiline, $leftbracket, $midlelement, $rightbracket)
    !if ($multiline==1)
         $leftbracket %newline() $midlelement $rightbracket
    !else
        $leftbracket $midlelement $rightbracket
    !endif    
    !endprocedure

    !unquoted procedure $optional($namecomponent,$multiline, $leftbracket, $midlelement, $rightbracket, $rule)
        !if ($rule==1)
            $mandatoryInternal($multiline, $leftbracket, $midlelement, $rightbracket) 
        !endif
    !endprocedure

    !unquoted procedure $alternative($namecomponent,$multiline,$leftbracket, $midlelement, $rightbracket, $rule, $namealternative, $leftalternative,$midlealternative,$rightalternative,$multialternative)
        !if ($rule==0) 
             $mandatoryInternal($multiline, $leftbracket, $midlelement, $rightbracket)
        !elseif ($rule==1)
            $mandatoryInternal($multialternative, $leftalternative, $midlealternative, $rightalternative)   
        !endif 
    !endprocedure

    !procedure $mandatoryJsonInternal($json)
    !if ($json.multiline==1)
         $json.leftbracket %newline() $json.midlelement $json.rightbracket
    !else
        $json.leftbracket $json.midlelement $json.rightbracket
    !endif    
    !endprocedure

    !procedure $optionalJsonInternal($json)
        !if ($json.rule==1)
            $mandatoryJson($json) 
        !endif
    !endprocedure

     !procedure $alternativeJsonInternal($json)
        !if ($json.rule==0) 
             $mandatoryJson($json)
        !elseif ($json.rule==1)
            $mandatoryInternal($json.multialternative, $json.leftalternative, $json.midlealternative, $json.rightalternative)   
        !endif 
    !endprocedure

    !unquoted procedure $mandatoryInternal($multiline, $leftbracket, $midlelement, $rightbracket)
    !if ($multiline==1)
         $leftbracket %newline() $midlelement $rightbracket
    !else
        $leftbracket $midlelement $rightbracket
    !endif    
    !endprocedure

     !unquoted procedure $optionalInternal($multi, $leftbracket, $midlelement, $rightbracket, $aparecer)
        !if ($aparecer==1)
            $mandatoryInternal($multi, $leftbracket, $midlelement, $rightbracket) 
        !endif
    !endprocedure

    !unquoted procedure $alternativeInternal($multi,$leftbracket, $midlelement, $rightbracket, $plataforma, $leftalternative,$midlealternative,$rightalternative, $multialternative)
        !if ($plataforma==0) 
             $mandatoryInternal($multi, $leftbracket, $midlelement, $rightbracket)
        !elseif ($plataforma==1)
            $mandatoryInternal($multialternative, $leftalternative, $midlealternative, $rightalternative)   
        !endif 
    !endprocedure

    !unquoted procedure $mandatoryInput($midlelement)
        "$midlelement"
    !endprocedure

    !unquoted procedure $optionalInput($midlelement, $aparecer)
        !if ($aparecer==1)
            $mandatoryInput($midlelement) 
        !endif
    !endprocedure

    !unquoted procedure $alternativeInput($midlelement, $plataforma, $midlealternative)
        !if ($plataforma==0) 
             $mandatoryInput($midlelement)
        !elseif ($plataforma==1)
            $mandatoryInput($midlealternative)   
        !endif 
    !endprocedure
}
@endsalt