@startsalt perfilfeature
{
!unquoted procedure $mandatory($multi, $leftbracket, $midlelement, $rightbracket)
    !if ($multi==1)
         $leftbracket %newline() $midlelement $rightbracket
    !else
        $leftbracket $midlelement $rightbracket
    !endif    

    !endprocedure

    !unquoted procedure $optional($multi, $leftbracket, $midlelement, $rightbracket, $aparecer)
        !if ($aparecer==1)
            $mandatory($multi, $leftbracket, $midlelement, $rightbracket) 
        !endif
    !endprocedure

    !unquoted procedure $alternative($multi,$leftbracket, $midlelement, $rightbracket, $plataforma, $leftalternative,$midlealternative,$rightalternative, $multialternative)
        !if ($plataforma==0) 
             $mandatory($multi, $leftbracket, $midlelement, $rightbracket)
        !elseif ($plataforma==1)
            $mandatory($multialternative, $leftalternative, $midlealternative, $rightalternative)   
        !endif 
    !endprocedure

    !$aparecer = 1
    !$desktop = 0

    $optional(0,"","%chr(34) Pesquise Aqui %chr(34) |","",$aparecer)

    $alternative(1,{*,Produtos | <b>Meu Carrinho | Meu Perfil,},$desktop,{*,<&menu> | <&cart>,},0)

    $mandatory(0,"","Nome:Fulano de Tal %newline() Endereço: Gotham City","")
}
@endsalt