@startsalt produtosfeature
{S
    !include https://raw.githubusercontent.com/JoseCarlosDeJesus/PLANTUML-features/main/EstudoDeCasoFeature/definitivefeature.puml


    !$desktop = 1
    !$aparecer = 1
    !$produto1 = { "titulo": "Notebook Gamer Lenovo" ,"disponivel": 50, "valor": "R$4699", "imagem": "http://plantuml.com/logo3.png"}
    !$produto2 = { "titulo": "Notebook Samsung Book" ,"disponivel": 20, "valor": "R$2549", "imagem": "http://plantuml.com/logo3.png"}

    $optional(0,"","%chr(34) Pesquise Aqui %chr(34) |","",$aparecer) |
    $alternative(1,"{*","Produtos | <b>Meu Carrinho | Meu Perfil","}",$desktop,"{*","<&menu> | <&cart> %newline() <&menu> | Produtos | Meu Carrinho | - | Meu Perfil","}",0)

    $mandatory(0,"",..,"")
    $mandatory(0,"",==,"")

    
    $mandatory(1,{^,"<img:$produto1.imagem> %newline() $produto1.titulo %newline() $produto1.disponivel %newline() $produto1.valor %newline() [Comprar]",})
    $mandatory(1,{^,"<img:$produto2.imagem> %newline() $produto2.titulo %newline() $produto2.disponivel %newline() $produto2.valor %newline() [Comprar]",})
     
}
@endsalt