@startsalt perfilInclude
{

    !include https://raw.githubusercontent.com/JoseCarlosDeJesus/PLANTUML-features/main/EstudoDeCasoFeature/definitivefeature.puml

    !$aparecer = 1
    !$desktop = 0

    $optional("nome",0,"","%chr(34) Pesquise Aqui %chr(34) |","",$aparecer)

    $alternative("outronome",1,{*,Produtos | <b>Meu Carrinho | Meu Perfil,},$desktop,{*,<&menu> | <&cart>,},0)

    $mandatory("aindaoutronome",0,"","Nome:Fulano de Tal %newline() Endereço: Gotham City","")
}
@endsalt