@startsalt featureinput
{
    !unquoted procedure $mandatoryInput($midlelement)
        "$midlelement"
    !endprocedure

    !unquoted procedure $optionalInput($midlelement, $aparecer)
        !if ($aparecer==1)
            $mandatoryInput($midlelement) 
        !endif
    !endprocedure

    !unquoted procedure $alternativeInput($midlelement, $plataforma, $midlealternative)
        !if ($plataforma==0) 
             $mandatoryInput($midlelement)
        !elseif ($plataforma==1)
            $mandatoryInput($midlealternative)   
        !endif 
    !endprocedure
    
    !$plataforma = 0
    $mandatoryInput(Oi meu amigo)
    $optionalInput(A vaca, 1)
    $alternativeInput(A abelha,$plataforma, O sabio)


}
@endsalt